apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: inner-circle-backend-staging
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/cloudsql-instances: PROJECT:REGION:INSTANCE
        autoscaling.knative.dev/minScale: "1"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
        - image: REGION-docker.pkg.dev/PROJECT/inner-circle/backend-staging:latest
          ports:
            - containerPort: 8080
          env:
            - name: NODE_ENV
              value: production
